{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "radarr.fullname" . }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
spec:
  groups:
    - name: {{ include "radarr.fullname" . }}
      rules:
        {{- toYaml .Values.metrics.prometheusRule.rules | nindent 8 }}
{{- end }}